In [1]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 83.,], [89., 91., 90.,], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [2]:
hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

train = optimizer.minimize(cost)

In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [4]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    
    if step % 20 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  161.57434 
Prediction:
 [[154.89465 ]
 [164.52744 ]
 [175.14276 ]
 [189.73586 ]
 [124.180504]]
20 Cost:  77.4579 
Prediction:
 [[162.99579]
 [174.04857]
 [184.78462]
 [200.22366]
 [131.71815]]
40 Cost:  76.5623 
Prediction:
 [[162.93579]
 [174.1174 ]
 [184.76228]
 [200.18922]
 [131.77454]]
60 Cost:  75.67709 
Prediction:
 [[162.87605]
 [174.18573]
 [184.73997]
 [200.15489]
 [131.83054]]
80 Cost:  74.80239 
Prediction:
 [[162.81665]
 [174.25362]
 [184.71777]
 [200.12076]
 [131.88618]]
100 Cost:  73.937965 
Prediction:
 [[162.75758]
 [174.32108]
 [184.69571]
 [200.08684]
 [131.94153]]
120 Cost:  73.083496 
Prediction:
 [[162.69884]
 [174.38815]
 [184.6738 ]
 [200.05315]
 [131.99657]]
140 Cost:  72.238976 
Prediction:
 [[162.64047]
 [174.45485]
 [184.65201]
 [200.01968]
 [132.05133]]
160 Cost:  71.4046 
Prediction:
 [[162.5824 ]
 [174.52106]
 [184.63034]
 [199.98639]
 [132.10574]]
180 Cost:  70.57987 
Prediction:
 [[162.52469]
 [174.58691]
 [184.60881]
 [199.95334]
 [132.15988]]
