In [2]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_batch, Y:y_batch})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  18050.2 
Prediction:
 [[19.526468]
 [30.589867]
 [26.472307]
 [28.619034]
 [25.310051]
 [19.235847]
 [19.16282 ]
 [10.820319]
 [30.018183]
 [28.020655]]
10 Cost:  19.521458 
Prediction:
 [[150.1432 ]
 [187.59021]
 [181.16081]
 [197.09604]
 [145.04332]
 [107.52625]
 [145.28479]
 [104.33454]
 [176.76036]
 [163.96158]]
20 Cost:  20.608824 
Prediction:
 [[151.02939]
 [188.64134]
 [182.20335]
 [198.2358 ]
 [145.8379 ]
 [108.11715]
 [146.14833]
 [104.98968]
 [177.74478]
 [164.88176]]
30 Cost:  20.540476 
Prediction:
 [[151.04013]
 [188.6401 ]
 [182.20908]
 [198.24634]
 [145.82991]
 [108.11624]
 [146.16658]
 [105.01813]
 [177.7456 ]
 [164.89078]]
40 Cost:  20.459099 
Prediction:
 [[151.04494 ]
 [188.63177 ]
 [182.2078  ]
 [198.2492  ]
 [145.81651 ]
 [108.111336]
 [146.17908 ]
 [105.042274]
 [177.73979 ]
 [164.89362 ]]
50 Cost:  20.378075 
Prediction:
 [[151.04971 ]
 [188.62343 ]
 [182.20647 ]
 [198.25204 ]
 [145.80312 ]
 [108.1064  ]
 [146.1915  ]
 [105.066315]
 [177.73393 ]
 [164.89

520 Cost:  16.991352 
Prediction:
 [[151.26672]
 [188.25046]
 [182.15031]
 [198.37717]
 [145.20735]
 [107.88066]
 [146.74028]
 [106.12812]
 [177.46605]
 [165.0035 ]]
530 Cost:  16.927607 
Prediction:
 [[151.2712  ]
 [188.24294 ]
 [182.14925 ]
 [198.37968 ]
 [145.1954  ]
 [107.875984]
 [146.75124 ]
 [106.149315]
 [177.46051 ]
 [165.00533 ]]
540 Cost:  16.864124 
Prediction:
 [[151.27565]
 [188.23541]
 [182.14818]
 [198.38217]
 [145.18344]
 [107.87133]
 [146.76216]
 [106.17046]
 [177.45496]
 [165.00714]]
550 Cost:  16.80095 
Prediction:
 [[151.28009]
 [188.2279 ]
 [182.1471 ]
 [198.38464]
 [145.17151]
 [107.86665]
 [146.77304]
 [106.19154]
 [177.44943]
 [165.00893]]
560 Cost:  16.738117 
Prediction:
 [[151.28455]
 [188.22043]
 [182.14604]
 [198.38713]
 [145.1596 ]
 [107.862  ]
 [146.78392]
 [106.21258]
 [177.44392]
 [165.01071]]
570 Cost:  16.675621 
Prediction:
 [[151.28897]
 [188.21297]
 [182.14497]
 [198.3896 ]
 [145.14775]
 [107.85735]
 [146.79475]
 [106.23354]
 [177.4384 ]
 [165.012

1030 Cost:  14.112651 
Prediction:
 [[151.4858 ]
 [187.8866 ]
 [182.1008 ]
 [198.49655]
 [144.63087]
 [107.64984]
 [147.26358]
 [107.14126]
 [177.19235]
 [165.07715]]
1040 Cost:  14.0632305 
Prediction:
 [[151.48993 ]
 [187.87987 ]
 [182.09993 ]
 [198.49875 ]
 [144.62025 ]
 [107.64548 ]
 [147.27315 ]
 [107.159805]
 [177.18716 ]
 [165.07823 ]]
1050 Cost:  14.014044 
Prediction:
 [[151.49403]
 [187.87314]
 [182.09908]
 [198.50093]
 [144.60965]
 [107.64112]
 [147.2827 ]
 [107.17831]
 [177.18199]
 [165.0793 ]]
1060 Cost:  13.9651 
Prediction:
 [[151.49815]
 [187.86644]
 [182.0982 ]
 [198.5031 ]
 [144.59908]
 [107.63675]
 [147.29222]
 [107.19675]
 [177.17683]
 [165.08037]]
1070 Cost:  13.916405 
Prediction:
 [[151.50223]
 [187.85974]
 [182.09735]
 [198.50526]
 [144.58852]
 [107.63241]
 [147.30173]
 [107.21514]
 [177.17166]
 [165.08139]]
1080 Cost:  13.867929 
Prediction:
 [[151.50635]
 [187.85306]
 [182.09648]
 [198.50742]
 [144.57799]
 [107.62806]
 [147.3112 ]
 [107.23349]
 [177.1665 ]
 [1

1530 Cost:  11.920785 
Prediction:
 [[151.68373 ]
 [187.56754 ]
 [182.06155 ]
 [198.59912 ]
 [144.1291  ]
 [107.43905 ]
 [147.71289 ]
 [108.011635]
 [176.94255 ]
 [165.11728 ]]
1540 Cost:  11.882289 
Prediction:
 [[151.68752]
 [187.5615 ]
 [182.06084]
 [198.60103]
 [144.11964]
 [107.43499]
 [147.72127]
 [108.0279 ]
 [176.93773]
 [165.11781]]
1550 Cost:  11.844027 
Prediction:
 [[151.6913  ]
 [187.5555  ]
 [182.06013 ]
 [198.60295 ]
 [144.11023 ]
 [107.43094 ]
 [147.72966 ]
 [108.044136]
 [176.93295 ]
 [165.11836 ]]
1560 Cost:  11.805937 
Prediction:
 [[151.69508]
 [187.5495 ]
 [182.05945]
 [198.60486]
 [144.10083]
 [107.4269 ]
 [147.738  ]
 [108.06033]
 [176.92816]
 [165.11887]]
1570 Cost:  11.768053 
Prediction:
 [[151.69885]
 [187.54352]
 [182.05875]
 [198.60678]
 [144.09146]
 [107.42287]
 [147.74635]
 [108.07648]
 [176.92337]
 [165.11938]]
1580 Cost:  11.7303295 
Prediction:
 [[151.70262]
 [187.53755]
 [182.05806]
 [198.60867]
 [144.0821 ]
 [107.41883]
 [147.75465]
 [108.09259]
 [17